### ISSUE TITLE
Bacalhau logs websocket error when clientid does not match job

### ISSUE THREAD

**Issue by thetechnocrat-dev** [bacalhau-project/bacalhau#2668] opened 2023-07-13 15:50 UTC
When I try to look at the logs I get the following error. It did work one time on a bacalhau job and has not worked since.

```bacalhau logs -f 472734f4-4615-40ec-8670-1c1ff41e0202```
```failed to read: websocket: close 1006 (abnormal closure): unexpected EOF%```

Note this is pointing towards our requester node, which requires running the following to test directly

export BACALHAU_API_HOST=54.210.19.52

**Comment by simonwo** [comment] 2023-07-13 16:47
Looking at this.

**Comment by simonwo** [comment] 2023-07-13 17:04
This is also happening on Bacalhau public demonnet, it's not just you. Investigating the regression.

**Comment by simonwo** [comment] 2023-07-13 17:22
@thetechnocrat-dev I think this is because the server silently enforces that the Client ID of the job submitter and the Client ID of the logs requester must match. Can you try running this against one of your own jobs and see if you can get the logs back?

I can't remember why this protection is there. Either way, we need to fix up the error message, CLI validation, and documentation.

**Comment by simonwo** [comment] 2023-07-13 17:22
cc @rossjones

**Comment by rossjones** [comment] 2023-07-13 20:48
Annoyingly in trying to return an error, it exceeds the maximum length for control messages and triggers another error which is the 1006 you're seeing.  I need to refactor a little to add error messages as explicit message types, but will take a look in the morning.

Do we want the current behaviour of blocking access to the logs for users who didn't start the job, or is it something we should remove until we've a better view on how to control access to all of the commands?

**Comment by thetechnocrat-dev** [comment] 2023-07-13 23:38
Thanks that makes sense. We had jobs getting triggered from a Google Colab Notebook and I was trying to monitor the logs from my local machine, which of course has a different client ID.

When I run the log command from the Google Colab Notebook terminal it does stream the logs 🎉 

The only downside from my perspective is that Google Colab requires the $9.99 a month Pro version to use the terminal feature. So, Google Colab users without a Pro version can't use the log streaming feature.

**Comment by rossjones** [comment] 2023-07-14 14:40
I've fixed the output of the error message, but will leave this issue open pending a decision on open access to logs or not.  

My gut feel is that it's type of thing we might encapsulate within the job somehow to mark the job as open to anyone accessing the logs (or output, or describe) - but probably needs further thought.

**Comment by thetechnocrat-dev** [comment] 2023-07-19 21:36
I do like the idea of having the ability to set the logs access at the job level.

**Comment by simonwo** [comment] 2023-07-31 14:36
Authorisation is a wider issue we will be tackling over the next few months and the result of that work should be a general approach to authz. In that case, I actually think we should remove this auth requirement for logs for now, under the logic that it's getting in the way of people doing stuff, and then come back to it when we implement general auth.

**Comment by aronchick** [comment] 2024-01-08 03:39
Did you address this with the authorization work?

**Comment by simonwo** [comment] 2024-01-08 03:51
It _will_ be addressed, but that work is in progress.

**Comment by wdbaruni** [comment] 2024-04-16 07:15
closing as noisy logs have been resolved, and auth is a wider topic addressed in multiple other issues

**Closed** 2024-07-01 09:26 UTC
