### ISSUE TITLE
Use of Filecoin+ For Implementing Filecoin Storage

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#449] opened 2022-08-06 17:25 UTC
ETA: 2023Q1

Proposal - somehow, we should figure out how to use Filecoin+ when storing. This will encourage a lot more storage providers to participate and run. Ideally then they ALSO might get first bid on storing (meaning they'll have more dedicated storage as well).

So, the way this might work would be:

1. User decides to use a dataset on FIL+
2. User engages with Bac to process the data
3. The derivative final data set is also stored on FIL+ (possibly?)

There's lots more to read about here - https://github.com/filecoin-project/FIPs/discussions/313

**Comment by wjam** [comment] 2022-10-28 08:20
Duplicate of #665?

**Closed** 2024-01-04 00:40 UTC
Labels: milestone, starmaps
