### ISSUE TITLE
When starting server on GCP, external IP not visible

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3558] opened 2024-03-02 21:15 UTC
```
dig +short myip.opendns.com @resolver1.opendns.com
```

Produces the correct external IP - but when I try to start:

```
IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
bacalhau serve --host $IP
```

I get:
```
2024/03/02 21:12:29 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
SDK 2024/03/02 21:12:30 WARN falling back to IMDSv1: operation error ec2imds: getToken, http response error StatusCode: 405, request to EC2 IMDS failed
SDK 2024/03/02 21:12:30 WARN falling back to IMDSv1: operation error ec2imds: getToken, http response error StatusCode: 405, request to EC2 IMDS failed
error starting node: listen tcp 34.71.149.24:1234: bind: cannot assign requested address
```

This is because my `ip addr` is:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP group default qlen 1000
    link/ether 42:01:0a:80:00:02 brd ff:ff:ff:ff:ff:ff
    altname enp0s4
    inet 10.128.0.2/32 scope global dynamic ens4
       valid_lft 2398sec preferred_lft 2398sec
    inet6 fe80::4001:aff:fe80:2/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by wdbaruni** [comment] 2024-06-26 14:01
duplicate of https://github.com/bacalhau-project/bacalhau/issues/3557

**Closed by wdbaruni** 2024-06-26 14:01 UTC
