### ISSUE TITLE
TestLotusNodeSuite/TestLotusNode is flaky

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#1705] opened 2023-01-19 00:31 UTC
Test often times out after 10 mins, see e.g. https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/3064/workflows/ba830836-1de4-41a4-a622-d45b8157691e/jobs/30586

**Comment by wjam** [comment] 2023-01-25 10:49
I think one of the causes of this issue is that each block must finish mining within 4 seconds, for the `localnet`, to be considered valid but it's possible for the CI instance to be too overloaded to mine fast enough.

Another issue I've spotted is that it takes roughly 4 minutes to perform this call https://github.com/filecoin-project/bacalhau/blob/430bbb06bebc6614bcdd3ad956157c23dc6b709b/pkg/publisher/filecoin_lotus/publisher.go#L295

**Comment by philwinder** [comment] 2023-01-25 12:58
I've seen this too: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1674649121250959

**Comment by wjam** [comment] 2023-02-06 12:18
The test has been marked as skip as it's been failing too much recently

https://github.com/filecoin-project/bacalhau/pull/1898

**Comment by frrist** [comment] 2023-06-06 22:07
We can close this when [#2538](https://github.com/bacalhau-project/bacalhau/issues/2538) is addressed as we are removing this storage option.

**Closed** 2023-06-21 00:48 UTC
Labels: testing, flake
