### ISSUE TITLE
Dylibso is noticing some tracing issues

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2960] opened 2023-10-27 04:30 UTC
Zach (cc'd) is making great progress on getting the Observe SDK traces merged with compute node (host) traces so they both show up in the same sink (in this case Jaeger) using the trace id configured by the host, however we've run into a couple of snags and could use your assistance.

Although some of traces from both the host (looks like mostly background tasks) and the wasm module are making into Jaeger, it's missing the context around the wasm execution and we're getting some otel errors from Bacalhau that look like the following:

```
13:33:47.323 | ERR pkg/telemetry/common.go:18 > Error occurred while handling spans error="traces export: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
13:34:37.327 | ERR pkg/telemetry/common.go:18 > Error occurred while handling spans error="traces export: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
```

We're having some trouble unwinding the source of the error as it appears that a [global error error handler](https://pkg.go.dev/go.opentelemetry.io/otel#SetErrorHandler) is being used. Also appears we're getting these errors on the main branch with the Observe SDK disabled as well. The Observe SDK is also reusing the Bacalhau Otel client config so we're reasonably confident both are using the same protocol (e.g. grpc/protobuf).

**Comment by simonwo** [comment] 2023-10-31 21:59
cc @zshipko @wikiwong

I've recreated the setup locally and checked out your fork. Tl;dr: I can't observe any issue, and the tracing seems to be working as intended (see below screenshot).

![image](https://github.com/bacalhau-project/bacalhau/assets/4951176/2e2b2226-4e24-49b6-b838-046d7ed63c98)

The telemetry errors you are seeing appear to be coming from inside the library that provides our IPFS node. When I remove the IPFS node (by running an external node instead) the errors disappear. So I believe you can safely ignore this – all of the traces from Bacalhau appear to be transmitting correctly.

I can see context around the WASM execution in the form of `pkg/compute.ExecutorBuffer.Run` as shown in the screenshot. Do you not get this? Are you expecting more/different context?

I can also see the Observe SDK traces appearing.

**Comment by zshipko** [comment] 2023-11-02 20:35
Thank you - using this setup it seems to work correctly!

Before I wasn't seeing the `pkg/compute.ExecutorBuffer.Run` events in jaeger, but maybe it is just a configuration issue. I was also using `bacalhau devstack` for my tests before.

Very excited to see this working!

**Comment by wikiwong** [comment] 2023-11-07 18:42
@simonwo after discussing further, we're going to make the tweak to utilize Bacalhau's OTel client for the Wasm tracing as well.  We'll notify once we get that in, do some additional testing, then sync back up to talk about next steps for getting this merged.  Let us know if there's anything else you'd like to see before getting this merged!

**Comment by simonwo** [comment] 2023-11-13 18:23
Thanks! I'm closing this issue now and we can continue discussion in the PR.

**Closed by simonwo** 2023-11-13 18:23 UTC
