### ISSUE TITLE
After killing a compute node, it restarts and gets a new ID, and the old one is not reaped.

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#4460] opened 2024-09-18 11:18 UTC
```
❯ v1.5.0/bacalhau node list
 ID          TYPE     APPROVAL  STATUS        LABELS                                              CPU     MEMORY      DISK         GPU
 n-0020de07  Compute  APPROVED  DISCONNECTED  Architecture=arm64 Operating-System=darwin          8.4 /   44.8 GB /   46.6 GB /    0 /
                                              name=compute1                                       8.4     44.8 GB     46.6 GB      0
 n-346f5e00  Compute  APPROVED  DISCONNECTED  Architecture=arm64 Operating-System=darwin          8.4 /   44.8 GB /   46.5 GB /    0 /
                                              name=compute1                                       8.4     44.8 GB     46.5 GB      0
 n-a4e0671b  Compute  APPROVED  CONNECTED     Architecture=arm64 Operating-System=darwin          8.4 /   44.8 GB /   46.4 GB /    0 /
                                                                                                  8.4     44.8 GB     46.4 GB      0
 n-b3514fcf  Compute  APPROVED  CONNECTED     Architecture=arm64 Operating-System=darwin          8.4 /   44.8 GB /   46.3 GB /    0 /
                                              name=compute1                                       8.4     44.8 GB     46.3 GB      0
```

Ideally, after the compute node restarts, the node gets the same name and ID it had before. It feels wrong that it changed.

**Comment by frrist** [comment] 2024-09-18 19:20
@aronchick when you kill the compute node are you bouncing the process or deleting the repo and spinning up a new one?

**Comment by aronchick** [comment] 2024-09-19 21:23
I shut the compute node down with control C

**Comment by frrist** [comment] 2024-09-23 20:22
I am unable to reproduce this locally, steps I followed are here: https://github.com/bacalhau-project/bacalhau/issues/4459#issuecomment-2362298064

**Comment by frrist** [comment] 2024-09-24 01:16
closing as I cannot reproduce this, feel free to re open with steps to reproduce.

**Closed by frrist** 2024-09-24 01:16 UTC
Labels: th/game-day
