### ISSUE TITLE
Have better errors around "no nodes with <StorageType> are available on the network"

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#2398] opened 2023-04-23 07:57 UTC
![image](https://user-images.githubusercontent.com/79689323/233827304-d1d6942b-7d1c-49ef-a735-f834ccd63536.png)

**Comment by frrist** [comment] 2023-04-25 22:27
Is this a duplicate of https://github.com/bacalhau-project/bacalhau/issues/2371?

Also, slight nit: In future issues provide the text in the issue rather than a screenshot, it makes it easier to search for the error in question e.g.
```logs
15:15:25.764 ERR pkg/requester/scheduler_state.go:103 > [transitionJobState] failed to find enough nodes to retry error-"not enough nodes to run job, requested: 1, avail
able: 0" [NodeID:QmZgkr18]
15:15:25.764 | ERR pg/requester/scheduler.go: 518 > error completing job d115889-d188-4087-92c8-656fb48eea41 error-"node QmfKYS1RL3G1yGnTVTQ1gLtQbUwSAKbWRQK2P7 JkgvLLza fa
iled due to: compute.AskforBidrequest: failed to decode response from peer OmfKyS1RL3G1yGnTVTO1gLtObUwSAKWROK2P7JkavLLza: stream reset" [NodeID:QmZgkr18] (stack: [ " func" :
"(*Basescheduler) .stopJob", "line": "518", "gource": "scheduler.go"), ("fune":" (*Basescheduler) checkForFailedExecutions. funci", "line": "96", "gource": "scheduler_state.go"), (" fun c":" (*Basescheduler) .checkForFailedExecutions", "line": "105", "source": "scheduler state.go"), ("func":" ("Basescheduler) .transitionJobstateLockFree", "line": "12"
"source": "sche
duler_state.go"), ("fune":" (*Basescheduler) transitionJobstate", "line": "21", "source": "scheduler_state.go"), ("fune": " (*Basescheduler) handleExecutionFailure"
"line": "510" "gource":"scheduler.go"), ("fune":" (*BaseScheduler) . doNotifyAskForBid", "line": "177", "source": "scheduler.go"), ("func": "goexit", "line": "1598", "source": "asm and64.s")]]
15:15:25.764 | INF pkg/eventhandler/chained handlers.go: 73 > Handled event [ClientID:] (EventName:Error] [HandleDuration:0.104946] [JobID:d115889f-d188-4087-92c8-656fb48ee a41] [NodeID:Om2gkr18] |SourceNodeID:OmZakr18hzcSam56ta7DZNtGJSiOz5BDo41XbrUPxKS4Vo] [Status: "node OmfRyS1RI3GlyGnTVT01qLtobUwSAkbWROK2P7JkavLLza failed due to: compute.As kForBidRequest: failed to decode response from peer OmfKy51RI3G1 yGnTVT01gLtobUwSAkbWROK2P7JkgvLLza: stream reset" [TargetNodeID:]
15:15:26.266 | IN pkg/publicapi/handlerwrapper/log_handler.go:32 [NodeID:QmZgkr18] [Request: ("ClientID": "dOe91377168bfceb07186f3da0044 fb61fccee62326829d0dfe41b10010bd
"Duration": 0, "Ipaddr": "34.172.162.113", "JobID": "a115889-d188-4087-92c8-656fb48eea41", "Method": "PoST", "NodeID": "Qm2gkr18h2C5qm56ta7DZNtGJSiQz5BDo41XbrUPKS4Vo", "Size": 1 007, "StatusCode": 200, "URI":"/requester/events", "User^gent": "Go-http-client/1.1"y
```

**Comment by simonwo** [comment] 2023-06-19 15:45
If I submit a job like: 
```yaml
Job:
  APIVersion: V1beta1
  Spec:
    Deal:
      Concurrency: 1
    Docker:
      Entrypoint:
      - sleep
      - "300"
      Image: ubuntu
    Engine: Docker
    Language:
      JobContext: {}
    Network:
      Type: None
    Publisher: Estuary
    PublisherSpec:
      Type: Estuary
    Resources:
      GPU: ""
    Timeout: 1800
    Verifier: Noop
    Wasm:
      EntryModule: {}
    Inputs:
    - Name: inputs
      StorageSource: LocalDirectory
    outputs:
    - Name: outputs
      StorageSource: IPFS
      path: /outputs
```

I get: 
```
% go run . create job-local.yaml        
Error executing job: failed to submit job: not enough nodes to run job. requested: 1, available: 0
exit status 1
```

So it's not clear why I have got the error. In #2487 we fixed the issue by printing the errors reported by individual nodes, we now need to apply the same sort of logic here (however, note that this error has come from the _requester_, i.e. we didn't reach out to any nodes).

This may involve updating the "ranking strategy" interface to include a reason for discarding nodes, and then printing a summary of why nodes have been discarded.

**Closed** 2023-06-21 09:44 UTC
Labels: bug
