### ISSUE TITLE
Switch scenario tests to only use the v2 API

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3428] opened 2024-02-08 11:01 UTC
Currently the scenario tests use a mixture of the v1 and v2 api client.
We should look at switching them over to solely v2.

**Comment by simonwo** [comment] 2024-02-29 07:43
Or maybe even turn them into Bash tests?

**Comment by wdbaruni** [comment] 2024-04-16 09:35
duplicate of https://github.com/bacalhau-project/expanso-planning/issues/535

**Closed by wdbaruni** 2024-04-16 09:35 UTC
