### ISSUE TITLE
CP onboarding should be a one-liner

### ISSUE THREAD

**Issue by enricorotundo** [bacalhau-project/bacalhau#900] opened 2022-10-17 10:12 UTC
Revised CP onboarding docs #607 emerged the relative complexity of running a node.

Ideally should be as easy as:

```bash
> curl https://get.bacahau.org/install.sh | sh
> bacalhau serve
```

In brief, No IPFS install, no shared peer ids, only use non-root ports, etc.
How to achieve that?

Tasks:
- [ ] Figure out codebase changes for supporting the above
- [ ] Update #607

See 🧵 : https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1665753037734779

**Comment by wdbaruni** [comment] 2022-11-11 03:59
linking this https://github.com/filecoin-project/bacalhau/issues/906#issuecomment-1311199879

**Comment by SvenDowideit** [comment] 2022-11-17 01:08
imo, there's another step - the environment variables should not be needed unless there isn't a local to node service to talk to, or if there's more than one to choose from (even there, defaults are good UX..)

(and ideally, `bacalhau serve` would not be a blocking run - my first attempt at playing died because my ssh session went away, and I wasn't really sure if I had cleanup to deal with, or what side effects there might be)

**Comment by enricorotundo** [comment] 2023-03-09 09:26
@wjam I believe you worked on this feature recently? Can we close?

**Comment by wjam** [comment] 2023-03-10 09:44
Yes, this looks like a duplicate of #1231

**Closed by wjam** 2023-03-10 09:44 UTC
Labels: documentation, UX
