### ISSUE TITLE
unclear what happened here with running a job

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#4443] opened 2024-09-17 16:56 UTC
```

❯ bacalhau-1.5.0 docker run \
        -i https://gist.githubusercontent.com/js-ts/ec6a58c9e0991ed27dce5ca11198a88c/raw/fe16cb212661a30c46309da60fdd055ba4648bc5/fake_logs.log \
        ubuntu cat /inputs/fake_logs.log
Job successfully submitted. Job ID: j-51ea5088-4e43-4ccd-b679-0036d28c763f
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

 TIME                 EXEC. ID    TOPIC              EVENT
 Sep 17 17:54:16.793  e-20888760  Running Execution  creating container: Error response from daemon: invalid moun
                                                     t config for type "bind": invalid mount path: 'v1.5.0/data-d
                                                     ir/compute/executions/j-51ea5088-4e43-4ccd-b679-0036d28c763f
                                                     /e-20888760-68fd-4197-9c96-6249aca6b463/1988692201/fake_logs
                                                     .log' mount path must be absolute
 Sep 17 17:54:16.954  e-958b65e6  Running Execution  creating container: Error response from daemon: invalid moun
                                                     t config for type "bind": invalid mount path: 'v1.5.0/data-d
                                                     ir/compute/executions/j-51ea5088-4e43-4ccd-b679-0036d28c763f
                                                     /e-958b65e6-8e9b-4c28-8343-89b94dbaa164/1037879273/fake_logs
                                                     .log' mount path must be absolute
 Sep 17 17:54:16.965              Scheduling         not enough nodes to run job. requested: 1, available: 1, sui
                                                     table: 0.
                                                     • Node n-a4e0671b: job already executed on this node more th
                                                     an once
Error: job failed

Job Results By Node:

• Node n-a4e0671b: creating container: Error response from daemon: invalid mount config for type "bind": invalid mount path:
                     'v1.5.0/data-dir/compute/executions/j-51ea5088-4e43-4ccd-b679-0036d28c763f/e-958b65e6-8e9b-4c28-8343-89b94dbaa164/1037879273/fake_logs.log' mount
                     path must be absolute

• Node n-a4e0671b: creating container: Error response from daemon: invalid mount config for type "bind": invalid mount path:
                     'v1.5.0/data-dir/compute/executions/j-51ea5088-4e43-4ccd-b679-0036d28c763f/e-20888760-68fd-4197-9c96-6249aca6b463/1988692201/fake_logs.log' mount
                     path must be absolute

To get more details about the run, execute:
	/Users/daaronch/code/bacalhau-versions/v1.5.0/bacalhau job describe j-51ea5088-4e43-4ccd-b679-0036d28c763f

To get more details about the run executions, execute:
	/Users/daaronch/code/bacalhau-versions/v1.5.0/bacalhau job executions j-51ea5088-4e43-4ccd-b679-0036d28c763f


```

**Comment by frrist** [comment] 2024-09-18 21:07
duplicate of https://github.com/bacalhau-project/bacalhau/issues/4457 moving discussion there.

**Closed by frrist** 2024-09-18 21:07 UTC
Labels: th/game-day
