### ISSUE TITLE
Config and environment handling is a mess

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#1474] opened 2022-12-06 11:35 UTC
We have some support for "environments":
https://github.com/bacalhau-project/bacalhau/blob/522d48728644a6e5274ed92189abc21b2fa1ce8a/pkg/system/environment.go#L14-L20

And in the same package we have _completely separate_ environments support for default config:
https://github.com/bacalhau-project/bacalhau/blob/522d48728644a6e5274ed92189abc21b2fa1ce8a/pkg/system/constants.go#L6-L10

...which config completely ignores:
https://github.com/bacalhau-project/bacalhau/blob/522d48728644a6e5274ed92189abc21b2fa1ce8a/pkg/config/config.go#L38-L43

...and which is completely separate to this other config:
https://github.com/bacalhau-project/bacalhau/blob/522d48728644a6e5274ed92189abc21b2fa1ce8a/pkg/system/config.go#L33

The command line client does use it, but references other environment variables:
https://github.com/bacalhau-project/bacalhau/blob/522d48728644a6e5274ed92189abc21b2fa1ce8a/cmd/bacalhau/root.go#L123-L124

This is all quite unintuitive and baffling! And has already caused a bug where the canary tests are targeting production when we thought they were targeting a local devstack.

We should refactor all of this into a sensible config system with consistent variables.

**Comment by binocarlos** [comment] 2022-12-06 11:39
I'm glad someone said this :smile:

having this stuff in code is a problem I think: https://github.com/filecoin-project/bacalhau/blob/3410552b101535b6c2c87aa024cffd37a02f564c/pkg/system/environment.go#L14

let's just do this: https://12factor.net/config

**Comment by simonwo** [comment] 2022-12-06 12:45
More:
https://github.com/filecoin-project/bacalhau/blob/main/pkg/ipfs/downloader.go#L93-L107

**Comment by simonwo** [comment] 2022-12-13 09:35
#1501 is another example.

**Comment by wjam** [comment] 2023-01-19 14:06
I would also argue the reams of command line arguments that some of the commands take are also an example of the configuration mess within Bacalhau at the moment. Remember that there is a finite limit on the size of a command line (4095).

IMO, we need to have something able to read in from both a file and from environment variables to make it easy to override parts of the configuration.

We also need to have the configuration file format documented _somewhere_.

We could try something like https://cuelang.org with something that could parse environment variables into struct fields?

**Comment by wjam** [comment] 2023-02-21 12:58
Another example is #2004. This issue occurs because log messages are written when attempting to parse/create configuration directories which is before logging has been configured because the logging format is also configurable.

I think part of the problem is that `system.InitConfig` is both attempting to read configuration and ensure various files are present, something that should probably happen in separate steps.

**Comment by frrist** [comment] 2023-11-15 17:53
closed via https://github.com/bacalhau-project/bacalhau/pull/2740

**Closed by frrist** 2023-11-15 17:53 UTC
Labels: tech-debt
